#!/usr/bin/env python3
"""Scan zephyr/patches/**/*.patch and regenerate zephyr/patches.yml.

Run from the RZI repository root:

  python3 scripts/generate-patch-manifest.py

Existing comments, author, email, and date fields are retained by path.
"""
from __future__ import annotations

import argparse
import hashlib
import re
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PATCH_ROOT = REPO_ROOT / "zephyr" / "patches"


def west_sha256(path: Path) -> str:
    with open(path, encoding="utf-8", newline=None) as fp:
        return hashlib.sha256(fp.read().encode("utf-8")).hexdigest()


def load_old(yml: Path) -> dict[str, dict]:
    """Load hand-maintained fields from existing entries, indexed by path."""
    if not yml.is_file():
        return {}
    text = yml.read_text(encoding="utf-8")
    old: dict[str, dict] = {}
    current: dict | None = None
    in_comments = False
    comment_lines: list[str] = []
    for line in text.splitlines():
        match = re.match(r"  - path: (\S+)", line)
        if match:
            if current:
                if comment_lines:
                    current["comments"] = "\n".join(comment_lines).rstrip()
                old[current["path"]] = current
            current = {"path": match.group(1)}
            in_comments = False
            comment_lines = []
            continue
        if current is None:
            continue
        if in_comments:
            if line.startswith("      "):
                comment_lines.append(line[6:])
                continue
            in_comments = False
        key_match = re.match(r"    (author|email|date|upstreamable): (.+)$", line)
        if key_match:
            current[key_match.group(1)] = key_match.group(2)
        elif re.match(r"    comments: \|", line):
            in_comments = True
    if current:
        if comment_lines:
            current["comments"] = "\n".join(comment_lines).rstrip()
        old[current["path"]] = current
    return old


def yaml_comment_block(text: str) -> list[str]:
    return ["    comments: |"] + [
        f"      {line}" if line else "      " for line in text.split("\n")
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description="Regenerate patches.yml from patches/")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=REPO_ROOT / "zephyr" / "patches.yml",
    )
    parser.add_argument("--author", default="rzi")
    parser.add_argument("--email", default="patches@rzi.local")
    args = parser.parse_args()

    files = sorted(PATCH_ROOT.rglob("*.patch"))
    if not files:
        raise SystemExit(f"no .patch under {PATCH_ROOT}")

    old = load_old(args.output)

    lines = [
        "# Generated by scripts/generate-patch-manifest.py for use by west patch.",
        "# Documentation: doc/west-patch.md",
        "checkout-command: git checkout .",
        'clean-command: ""',
        "",
        "patches:",
    ]
    for patch_file in files:
        relative_path = patch_file.relative_to(PATCH_ROOT).as_posix()
        module = relative_path.split("/", 1)[0]
        previous = old.get(relative_path, {})
        stamp = previous.get("date") or date.fromtimestamp(
            patch_file.stat().st_mtime
        ).isoformat()
        comments = previous.get("comments") or (
            f"Automatically registered from {relative_path}; update this comment."
        )
        lines += [
            f"  - path: {relative_path}",
            f"    sha256sum: {west_sha256(patch_file)}",
            f"    module: {module}",
            f"    author: {previous.get('author', args.author)}",
            f"    email: {previous.get('email', args.email)}",
            f"    date: {stamp}",
            f"    upstreamable: {previous.get('upstreamable', 'true')}",
            "    apply-command: git apply",
            *yaml_comment_block(comments),
            "",
        ]

    args.output.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {args.output} ({len(files)} patches)")


if __name__ == "__main__":
    main()
